apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: data-registration-pipeline-
spec:
  schedule: "*/10 * * * *" # サンプルとして10分置きに実行。
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: pipeline
    templates:
      - name: pipeline
        steps:
          - - name: data-registration
              template: data-registration
      - name: data-registration
        initContainers:
          - name: data-registration-init
            image: shibui/building-ml-system:beverage_sales_forecasting_data_registration_1.0.0
            imagePullPolicy: Always
            command:
              - bash
              - -c
              - |
                mkdir -p /opt/data/
                wget https://storage.googleapis.com/beverage_sales_forecasting/data/item_sale_records_202107_202112.csv -P /opt/data/
            volumeMounts:
              - mountPath: /opt/data/
                name: data
        container:
          image: shibui/building-ml-system:beverage_sales_forecasting_data_registration_1.0.0
          imagePullPolicy: Always
          command:
            - "python"
            - "-m"
            - "src.main"
            - "--item_sales_records_path"
            - "/opt/data/item_sale_records_202107_202112.csv"
            - "--latest_week_only"
          env:
            - name: POSTGRESQL_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: password
            - name: POSTGRESQL_DBNAME
              value: beverage_sales_forecasting
          resources:
            requests:
              memory: 500Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /opt/data/
              name: data
        volumes:
          - name: data
            emptyDir: {}

    imagePullSecrets:
      - name: regcred
