apiVersion: apps/v1
kind: Deployment
metadata:
  name: similar-image-search-proxy
  namespace: search
  labels:
    app: similar-image-search-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: similar-image-search-proxy
  template:
    metadata:
      labels:
        app: similar-image-search-proxy
    spec:
      containers:
        - name: similar-image-search-proxy
          image: shibui/building-ml-system:ai_animals_search_similar_image_search_proxy_0.0.0
          imagePullPolicy: Always
          command:
            - "./run.sh"
          ports:
            - containerPort: 10000
          resources:
            limits:
              cpu: 1000m
              memory: "1000Mi"
            requests:
              cpu: 500m
              memory: "500Mi"
          env:
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: aianimals
            - name: REDIS_HOST
              value: redis.data.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: RUN_ENVIRONMENT
              value: cloud
            - name: PORT
              value: "15000"
            - name: WORKERS
              value: "2"
            - name: TIMEOUT
              value: "10"
            - name: LOG_LEVEL
              value: INFO
            - name: PSEUDO_PREDICTION
              value: "0"
            - name: MLFLOW_PARAM_JSON
              value: "{}"
            - name: PREDICTOR_URL
              value: http://similar-image-search-serving.search.svc.cluster.local:8501/v1/models/similar_image_search:predict
            - name: PREDICTOR_HEIGHT
              value: "224"
            - name: PREDICTOR_WIDTH
              value: "224"
            - name: THRESHOLD
              value: "100"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: similar-image-search-proxy
  namespace: search
  labels:
    app: similar-image-search-proxy
spec:
  ports:
    - name: similar-image-search-proxy
      port: 15000
      protocol: TCP
  selector:
    app: similar-image-search-proxy
