version: "3"

services:
  postgres:
    image: postgres:13.4
    container_name: postgres
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - default
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beverage_sales_forecasting
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    ports:
      - 5432:5432
    hostname: postgres
    restart: always
    stdin_open: true

  data_registration:
    container_name: data_registration
    image: shibui/building-ml-system:beverage_sales_forecasting_data_registration_1.0.0
    restart: "no"
    networks:
      - default
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DBNAME=beverage_sales_forecasting
      - LOG_LEVEL=DEBUG
    command: >
      /bin/sh -c "sleep 10s && python \
       -m src.main \
       --init_sql_file_path /opt/data/create.sql \
       --region_store_file_paths /opt/data/regions.csv /opt/data/stores.csv \
       --item_file_paths /opt/data/items.csv /opt/data/item_prices.csv \
       --item_sales_records_path /opt/data/item_sale_records_2017_2019.csv"
    volumes:
      - "./master_data:/opt/data"
    depends_on:
      - postgres

  bi:
    container_name: bi
    image: shibui/building-ml-system:beverage_sales_forecasting_bi_1.0.0
    restart: always
    networks:
      - default
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DBNAME=beverage_sales_forecasting
      - LOG_LEVEL=DEBUG
    command: >
      /bin/sh -c "sleep 30s &&  streamlit run src/main.py"
    ports:
      - 8501:8501
    depends_on:
      - data_registration

  mlflow:
    container_name: mlflow
    image: shibui/building-ml-system:beverage_sales_forecasting_mlflow_1.0.0
    volumes:
      - ./ml/outputs/mlruns:/opt/outputs/mlruns
    command:
      - "mlflow"
      - "server"
      - "--backend-store-uri"
      - "postgresql+psycopg2://user:password@postgres:5432/mlflow"
      - "--default-artifact-root"
      - "/opt/outputs/mlruns"
      - "--host"
      - "0.0.0.0"
    ports:
      - 15000:5000
    restart: always
    hostname: mlflow
    depends_on:
      - postgres

  ml:
    container_name: ml
    image: shibui/building-ml-system:beverage_sales_forecasting_ml_1.0.0
    restart: "no"
    volumes:
      - ./data:/opt/data
      - ./ml/hydra:/opt/hydra
      - ./ml/outputs:/opt/outputs
    networks:
      - default
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DBNAME=beverage_sales_forecasting
      - LOG_LEVEL=INFO
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: /bin/sh -c "sleep 30s && python -m src.main"
    depends_on:
      - data_registration
      - mlflow

networks:
  default:
    name: ml
