apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: aianimals
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: shibui/building-ml-system:ai_animals_api_0.0.0
          imagePullPolicy: Always
          command:
            - "./run.sh"
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 1000m
              memory: "2000Mi"
            requests:
              cpu: 500m
              memory: "500Mi"
          env:
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: aianimals
            - name: REDIS_HOST
              value: redis.data.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: RABBITMQ_HOST
              value: rabbitmq-amqp.data.svc.cluster.local
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              value: password
            - name: ES_HOST
              value: https://elastic-search-es-http.elastic-search.svc.cluster.local:9200
            - name: ES_SCHEMA
              value: https
            - name: ES_VERIFY_CERTS
              value: "0"
            - name: ES_USER
              value: elastic_user
            - name: ES_PASSWORD
              value: password
            - name: ANIMAL_REGISTRY_QUEUE
              value: animal
            - name: ANIMAL_VIOLATION_QUEUE_NO_ANIMAL_VIOLATION
              value: no_animal_violation
            - name: LEARN_TO_RANK_URL
              value: http://learn-to-rank-lgbm-regression.search.svc.cluster.local:11000/v0/reorder
            - name: GCS_BUCKET
              value: aianimals
            - name: RUN_ENVIRONMENT
              value: cloud
            - name: PORT
              value: "8000"
            - name: WORKERS
              value: "4"
            - name: TIMEOUT
              value: "15"
            - name: LOG_LEVEL
              value: INFO
            - name: KEY_FILE_PATH
              value: /opt/secrets/secret.key
          volumeMounts:
            - name: auth-secret
              mountPath: /opt/secrets
              readOnly: true
      volumes:
        - name: auth-secret
          secret:
            secretName: auth-secret
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: aianimals
  labels:
    app: api
spec:
  ports:
    - name: api
      port: 8000
      protocol: TCP
  selector:
    app: api
