apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-registry
  namespace: aianimals
  labels:
    app: search-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-registry
  template:
    metadata:
      labels:
        app: search-registry
    spec:
      containers:
        - name: search-registry
          image: shibui/building-ml-system:ai_animals_data_registry_0.0.0
          imagePullPolicy: Always
          command:
            - "python"
            - "-m"
            - "src.main"
            - "--job"
            - "animal_to_search_job"
          resources:
            limits:
              cpu: 500m
              memory: "500Mi"
            requests:
              cpu: 200m
              memory: "300Mi"
          env:
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: aianimals
            - name: REDIS_HOST
              value: redis.data.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: RABBITMQ_HOST
              value: rabbitmq-amqp.data.svc.cluster.local
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              value: password
            - name: ES_HOST
              value: https://elastic-search-es-http.elastic-search.svc.cluster.local:9200
            - name: ES_SCHEMA
              value: https
            - name: ES_VERIFY_CERTS
              value: "0"
            - name: ES_USER
              value: elastic_user
            - name: ES_PASSWORD
              value: password
            - name: RUN_ENVIRONMENT
              value: cloud
            - name: LOG_LEVEL
              value: INFO
            - name: DATA_DIRECTORY
              value: /opt/dataset/data/
            - name: ANIMAL_REGISTRY_QUEUE
              value: animal
      imagePullSecrets:
        - name: regcred
